### ISSUE TITLE
Greenday "Stands"ID Loads up with sometimes 21, 19 or 31 events

### ISSUE THREAD

**Issue by marcoboy123** [Caeden117/ChroMapper#163]
![ChroMapper_qJN5wcSG7A](https://user-images.githubusercontent.com/37511260/95667984-bde25680-0b6d-11eb-9a30-d6a3982e3515.png)
![Beat_Saber_agwouKbNEn](https://user-images.githubusercontent.com/37511260/95667985-c20e7400-0b6d-11eb-87a3-74c70dd29359.png)
Either im too high, but. This is kinda complicated. The Static Boxlights are neither values 1-4 nor the last events aswell. If you can replicate this easily aswell, just load up Greenday place some blocks in the id, and reload, and sometimes the amount of Stands ID will change.

**Comment by marcoboy123** [comment]
https://puu.sh/GBJYa/844af5aedd.png

**Comment by Caeden117** [comment]
This is a problem that will take quite a bit of time to fix, since the only viable solution that would solve both this issue, and the discrepancy between prop IDs in CM VS prop IDs in Beat Saber, is to manually assign each light in every environment to the correct prop ID. Not only that, but this would have to be checked every Beat Saber update to ensure that it is still accurate. 

While I wont close this issue, do be warned that it will be a _long_ while for it to be properly addressed.

**Comment by Top-Cat** [comment]
This is no longer random in CM but they _are_ random in beat saber so...
https://github.com/Aeroluna/Chroma/pull/5

**Comment by Caeden117** [comment]
Closing due to age, this should have been fixed a long time ago (Feel free to re-open if issue persists)
