### ISSUE TITLE
How do you use noodle extentions

### ISSUE THREAD

**Issue by SpaceByteDev** [Caeden117/ChroMapper#218]
Tried this because I wanted to do some cool things with it, and use noodle extensions, but I can't find a single mention of noodle extensions in the program, or how to use noodle extensions, any help?

**Comment by Top-Cat** [comment]
From the readme:
>I currently do not recommend (or endorse) cloning and building ChroMapper outside of development purposes. If you are building ChroMapper with the sole intention to map with it, you will not get support. If you would like support for ChroMapper, please consider joining Closed Beta.

**Comment by Caeden117** [comment]
Hi. Unfortunately, ChroMapper does not support visualization for newer Noodle Extensions features. Even more unfortunately, it does not even include tools for a lot of Noodle Extensions features. In reality, Noodle Extensions is so advanced that trying to encapsulate all of its features in a sane and user-friendly way would be extremely difficult.

ChroMapper has a catch-all solution in the form of the Node Editor, which allows manual JSON editing of each object, right within the editor. However, this is an extremely manual solution, and since ChroMapper does not support in-editor visualizations for newer Noodle Extensions features, it would feel similar to using a text editor. Thankfully, ChroMapper can let you add and modify your level and save changes without losing the Noodle Extensions components; you do not get this luxury with MMA2.

If you are looking to use ChroMapper exclusively for Noodle Extensions, let me be honest here: Because Noodle Extensions is so complex, you would be much better off with trying to artificially create your map with scripts.

I would personally recommend [Nyri0's mapping scripts](https://github.com/Nyrio/beat-saber-mapping-scripts), which he used to create his own levels, and also very generously open sourced for others to use. He uses Blender to easily create the scenery, and a Python script to convert the Blender objects into Noodle Extensions walls. I guarantee you that every single map that uses fancy Noodle Extensions modchart features are done with scripts.

You can also use a command line tool like [BeatWalls](https://github.com/spookyGh0st/beatwalls), which greatly speeds up wallmap creation. Like ChroMapper, BeatWalls only supports a small subset of what Noodle Extensions can do; however you can see an accurate visualization if you use BeatWalls with ChroMapper. This is what a lot of mappers use if you don't care much for modcharts.

I deeply apologize if this comes across as a big disappointment.
