### ISSUE TITLE
macOS app not working

### ISSUE THREAD

**Issue by EricE549X** [Caeden117/ChroMapper#349]
**ChroMapper version**
0.8.0 (first open beta)

**Describe the Issue**
i downloaded the macOS version of the chromapper launcher, only to encounter an error whenever i try to open it.

**Provide Screenshots or Videos**
<img width="372" alt="Screen Shot 2021-10-07 at 6 35 42 AM" src="https://user-images.githubusercontent.com/86898409/136509798-f9a710eb-9a57-4f08-8cd1-998997621c7a.png">
stacktrace log(?) from macOS console:
> handle LS launch error: {\n    AppPath = "/Users/erice549/Downloads/CML.app";\n    ErrorCode = "-10810";\n}

**Steps to Reproduce**
1. go to [launcher download page](https://cm.topc.at/dl)
2. select OS X version
3. decompress .zip
4. open .app file
5. see error

**Expected Behavior**
i expected it to open properly.

**Additional Context**
might have to do with the .exe launcher file, which is incompatible with macOS, being in the .app "package." idk tho i'm not good with code

i'm also on the macOS monterey beta in case OS version info is relevant

**Comment by sillyredcar** [comment]
Are you using an M1 mac?
If so, I was able to open CML on my M1 mac after I used this terminal command "sudo chmod -R 755 /path/to/CML/app" and typed in my password.

One other important thing is that If I try to open Chromapper by clicking on the Chromapper app instead of using CML it causes my computer to crash because of a process panic. So use CML to launch Chromapper every time.

**Comment by EricE549X** [comment]
i’m using an intel mac, specifically the 12-inch macbook (2017). i tried a different sudo command, but not the one you said. i’ll try that soon.

**Comment by EricE549X** [comment]
so the command "sudo xattr -rd com.apple.quarantine /Applications/my_app.app" worked, but it says i need a beat saber installation for it to work. any way to emulate it on mac?
