### ISSUE TITLE
Back Lights on the Fit Beat environment are reversed

### ISSUE THREAD

**Issue by AlephCubed** [Caeden117/ChroMapper#376]
ChroMapper version: V0.8.454

Issue: Back Lights on the Fit Beat environment are reversed. So when you use a red light on the back lasers, the light turns blue, and vice versa. (This effects the light preview in Chromapper and the map in game)

Video: https://user-images.githubusercontent.com/76791009/153775078-217e3df8-2066-4c7f-b474-5f02fb043c6f.mov

Steps to Reproduce: Create a map with the Fit Beat environment. Put a On Lighting event in the Back Lasers row. The lasers will be the opposite color of the event.

Expected Behavior: The light should be the same color as the event.

**Comment by Caeden117** [comment]
This is intentional design by Beat Games' part, and is present in other environments too. It was their early compromise of having "multiple colors" per environment, before compromising again with the Boost Lights system.

ChroMapper is just showing you how it would look in game. It's as simple as that.
