### ISSUE TITLE
ADB is not closed when Chromapper is closed

### ISSUE THREAD

**Issue by Silver-Volt4** [Caeden117/ChroMapper#418]
**ChroMapper version**
v0.8.489

**Describe the Issue**
ADB is not closed when Chromapper is closed. This leaves an adb.exe process in the task manager.
Most notably, it will prevent any actions on Chromapper's install folder (moving, renaming)

**Provide Screenshots or Videos**
![obrazek](https://user-images.githubusercontent.com/35656715/189688816-156303a0-0846-4931-9c00-c485f69116f1.png)

**Steps to Reproduce**
Set up CM to use ADB (I did this on first run), then open and close CM

**Expected Behavior**
No dangling process

**Comment by Fernthedev** [comment]
I wouldn't exactly say this is a bug, since it's how `adb` is supposed to work (it's a daemon). I guess the `adb` process could be a subprocess of CM which would close it when CM closes though. (at least, I assume)

How does this cause a problem for CM though? It doesn't rename the executable to my knowledge and it does properly kill the process if one were to uninstall it within CM last I checked.

**Comment by Silver-Volt4** [comment]
> How does this cause a problem for CM though?
Windows locks the quest-utils folder. Mine is in the same directory as the main executable. When I tried moving CM's install folder, I was denied because it was "open in another program", that program being the ADB process.
