### ISSUE TITLE
CML.EXE contains a trojain! Bearfoos.A!ml

### ISSUE THREAD

**Issue by dylanforcegaming** [Caeden117/ChroMapper#496]
**ChroMapper version**
*unkmown but latest of this date*

**Describe the Issue**
Detected Trojain: Trojan:Win32/Bearfoos.A!ml
Details: This program is dangerous and executes commands from an attacker.
Affected items: file: C:\Users\*Confidential*\Downloads\CML.exe (Installer File)
**Provide Screenshots or Videos**
![image](https://github.com/Caeden117/ChroMapper/assets/153900939/604a92c5-445f-4ed9-aa76-47ebcd4c7d03)

Expected Behavior
Run Installer - open chromapper - make maps - export to beat saver

What Happened
*Installs Exe* - (Windows Security) Trojain Detected! - *tries to kill file* -  *regains ability* -  *Tries For 5 mins* - *finally kills file*
**Additional Context**
i've had my expectations with this program but after a while i reinstalled it and it gave me a trojain. i have lost respect for this and will not be using it for futher use untill fixed, thank you.

**Comment by Caeden117** [comment]
The [ChroMapper Launcher source code is available here](https://github.com/Top-Cat/CMLauncher/). You can verify the source code yourself to conclude that it is not a "trojain".

Windows Defender is likely tripping over one (or more) of these things:

- ChroMapper Launcher modifies ChroMapper's internal files. This is how updates are delivered.
- ChroMapper Launcher launches a separate process, being ChroMapper itself.
- You installed ChroMapper Launcher in the Windows `Downloads` folder. Windows Defender is very suspicious of executables in the Download folder for very obvious reasons.

Furthermore, you can verify that your ChroMapper Launcher is verified and safe by checking its digital signature. ChroMapper Launcher is signed by Top Cat.

![image](https://github.com/Caeden117/ChroMapper/assets/30004286/22aba8fe-19e0-474d-944c-8f676af0d1e6)

Unfortunately, there is not a lot we can do on our end to prevent Windows Defender from flagging the Launcher as malicious. My personal recommendation is to move the ChroMapper Launcher outside of the `Downloads` folder and try again. Safe places usually include any secondary mass storage drive, `C:\Program Files`, or your Desktop folder.

If none of this convinces you otherwise, please consider building ChroMapper from source by following the [build guide](https://github.com/Caeden117/ChroMapper/blob/master/BUILD.md), if that gives you peace of mind.

**Comment by dylanforcegaming** [comment]
@Caeden117 ok thank you, but i think id recommend that in the next update its included that it can get flagged as a trojain. i think it would help alot of people and reassure them!👍

**Comment by dylanforcegaming** [comment]
@Caeden117 hey ive tried but it wont open because it thinks its a virus
