### ISSUE TITLE
Freezing upon opening the Editor

### ISSUE THREAD

**Issue by iroxOfficial** [Caeden117/ChroMapper#535]
**ChroMapper version**
What version of ChroMapper are you running? It can be seen by pressing `Escape` in the Editor, or on the bottom right of the Options menu. If you clone and built ChroMapper from the source, what commit did you clone from?

Latest

**Describe the Issue**
Type a clear and concise description of what the problem is.

When opening the Editor, it just freeze at loading part

**Provide Screenshots or Videos**
Providing screenshots and videos (especially if you are encountering an error message) will help a lot to helping us debug the issue.

If the Development Console is open and showing errors, ***PLEASE*** click on the specific error to open the Stack Trace. The "Stack Trace" is the exact location in ChroMapper's code that caused the error, and how it was executed. Providing the Stack Trace with your bug report will allow us to immediately find and fix the problem.

https://github.com/Caeden117/ChroMapper/assets/172177933/4f8b9700-9c16-4846-8237-4955526be28b

**Steps to Reproduce**
Describe the exact steps which reproduce the problem in as many details as possible.

simple, open the editor

**Expected Behavior**
What did you expect to happen? How did this differ from what actually happened?

open the editor

**Additional Context**

It only started happeing when i factory reseted windows

**Comment by XAce1337manX** [comment]
"Latest" is not a version number.
Few things to check:
1. Make sure you don't have any incompatible plugins. If you're not sure, remove them all and try again.
2. If that fails, it's probably due to the spectrogram using too much vram and crashing the gpu. Some versions of CM isn't detecting the sample quality it should be using correctly. Try lowering the Sample Quality in settings.
3. If that fails, then launch CM with a `-force-d3d11` argument

**Comment by iroxOfficial** [comment]
It worked. Thanks
