### ISSUE TITLE
Editing Event broken

### ISSUE THREAD

**Issue by Xavjer** [Caeden117/ChroMapper#57]
Various issues seen:

1. Is it normal, that if I select the first element with Ctrl+Shift+LeftMouse that the PopUp always appears?

2. Writing seems pretty broken within Unity2019 , when I start typing at the end of a line, it will write at the beginning of the line like on a new layer behind the existing text. Pressing the Left Arrow (Back 1 Character) once and then start typing, it is working correctly.

3. Some Keystrokes seem to trigger their events (Right Shift, P for example), they should be disabled while writing

**Comment by Caeden117** [comment]
Are you talking about Node Editor? If so:

1. Yes, there is a dedicated Node Editor Keybind option that limits this to the N key
2. That might be because the `OnFocus - Select All` option is enabled, which I'm 99% sure I disabled for Node Editor. However I am confused on what you mean here
3. There is no option to completely disable the `Input` class when focusing on an input field, so we would have to add condition checks every single time we want to check input, which is a pain in the ass since there's little bits of Input code dotted throughout CM from before I started the KeybindsController class (I believe `CameraController` and `AudioTimeSyncController` has input checks)

**Comment by Xavjer** [comment]
1. => Ok then, I understood this option that the Node Editor wouldn't be available unless this is actually set (As probably most of the user's won't bother having the editor, only advanced users)
2. and 3. combined :) https://streamable.com/yux8t

**Comment by Caeden117** [comment]
Alright, so this will take a bit of explaining to do.

The JSON library ChroMapper uses (SimpleJSON) uses a StringBuilder and calls `AppendLine()` whenever a new line for JSON is necessary.

Looking at the [Microsoft docs for this function](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.appendline?view=netframework-4.8), it is revealed that it appends the "default line terminator" to the end of the line, which [another search](https://stackoverflow.com/questions/7304724/writeline-method) reveals to be `\r\n`, instead of the expected `\n`.

`\r` is Carriage Return, pretty much how you jump to the leftmost (or rightmost) side of the file. 

TextMeshPro automatically treats `\n` as a new line, and removes it from the text you are editing, but it doesn't do the same for `\r`. Thus, if you click on the end of the line, the pointer will be positioned behind this `\r` character. Finally, when you try to add more content to the Node Editor, the new text will appear on the left side as if it *was* a new line, but instead is being written to the same line. This is "intended" behavior for `\r`, however not the behavior we want. Furthermore, if you try deleting content from the end of the line, you'd notice it will take one more backspace then usual to actually start deleting text; this is because you are deleting the hidden `\r` character.

So to fix it we just remove `\r`. Now Node Editor works properly.
